# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c79678f3a507715dc9380f6987b21cd9b0a3a8c030ce657143f3e28ad73005edc496ca1f886c3e45059138334d45d05bae4aed0808faee36f5922032d7fb3610

test:
  secret_key_base: 3c4ecd92ac96cd1288a0e45dcbd1e482d2e747ab96fe829e7762f4f9e54afd349ced9b3e61833c4ac8f5974633e0424eeb52c3e5e83a2e75aee843b2e0d3e253

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
